services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "5102:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=database;Database=DevApiDb;User=sa;Password=YourStrong@Passw0rd123;TrustServerCertificate=true
    depends_on:
      - database

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "5202:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5102
    depends_on:
      - api

volumes:
  sqlserver_data:
